spring:
  application:
    name: deep-learning
  profiles:
    active: local
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 15MB
#      max-request-size: 16MB
app:
  version: 1.0.0
  template:
    quantity-limit: 10
  isSaveAllImages: true
  aiThreadPoolSize: 1
  model:
    rootDirectory: ./.models